# Generated by Django 4.1.7 on 2023-03-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_hotelimages_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(default='New Delhi', max_length=100),
        ),
    ]
